[hsr]
name = "Honkai: Star Rail"
search_dirs = [
    # Linux - native launchers
    ".local/share/honkers-railway-launcher",
    # Linux - Steam / Proton
    ".local/share/Steam/steamapps/compatdata",
    ".steam/steam/steamapps/compatdata",
]
path_hints = ["Star Rail", "StarRail", "HSR", "honkers-railway"]

[gi]
name = "Genshin Impact"
search_dirs = [
    # Linux - native launchers
    ".local/share/anime-game-launcher",
    # Linux - Steam / Proton
    ".local/share/Steam/steamapps/compatdata",
    ".steam/steam/steamapps/compatdata",
]
path_hints = ["Genshin Impact", "GenshinImpact", "genshin"]

[wuwa]
name = "Wuthering Waves"
search_dirs = [
    # Linux - Steam
    ".local/share/Steam/steamapps/common/Wuthering Waves",
    ".steam/steam/steamapps/common/Wuthering Waves",
]
path_hints = ["Wuthering Waves", "WutheringWaves", "wuwa"]
